# You can find more wallpapers in ~/.config/biglexj/wallpapers/
# Run ~/.config/hypr/reload-hyprpaper.sh after changing your wallpaper
#preload = ~/.config/biglexj/wallpapers/wallpaper.jpg
#wallpaper = ,~/.config/biglexj/wallpapers/wallpaper.jpg
#splash = false
