#################
### AUTOSTART ###
#################

# Load configuration from ML4W Hyprland Settings App

#exec = ~/.config/ml4w-hyprland-settings/hyprctl.sh

exec-once = hypridle
exec-once = swaynccxz
exec-once = swww-daemon
exec-once = udiskie
exec-once = waybar
exec-once = dunst
exec-once = yin-yang --restore &
#exec-once = mpvpaper --restore &
#exec-once = waypaper --restore &
#exec-once = hyprpaper


exec-once = ~/.config/biglexj/wallpaper-conf/set_wallpaper.sh
exec-once = ~/.config/biglexj/notifications/battery-status.sh
exec-once = ~/.config/biglexj/wallpaper-conf/random_wallpaper.sh
exec-once = ~/biglexj/.config/swaync/start-swaync.sh

exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dbus-update-activation-environment --systemd HYPRLAND_INSTANCE_SIGNATURE #hyprshade

exec = hyprshade auto #color amarillo
