#source = $HOME/.cache/wal/colors-hyprland.conf

color0 = #111111
color1 = #222222
color2 = #333333
color3 = #444444
color4 = #555555
color5 = #666666
color6 = #777777
color7 = #888888


background {
    monitor =1800
    # color = $color1

    # all these options are taken from hyprland, see https://wiki.hyprland.org/Configuring/Variables/#blur for explanations
    blur_size = 4
    blur_passes = 3 # 0 disables blurring
    noise = 0.0117
    contrast = 1.3000 # Vibrant!!!
    brightness = 0.8000
    vibrancy = 0.2100
    vibrancy_darkness = 0.0
}

image {
    monitor = 
    path = /mnt/ntfs/Imágenes/Pictures/16.09/KANOKARI-Hypr.jpg # Path to your image - tiene que ser el mismos tamaño de tu pantalla
    size = 1800
    rounding = 0    # 0 para mantener las esquinas rectas, -1 para círculo completo
    border_size = 0
    rotate = 0
    reload_time = 0 # 0 deshabilita la recarga automática
    reload_cmd =   # puedes especificar un comando para actualizar la imagen si lo necesitas
    
    zindex = 0
}

label {
    text = "<b><big>Hola $USER</big></b>"
    font_family = Fira Sans
    color = #00FF00
    font_size = 44
    position = 0, -100 #Las posicion son en x e y, en pixeles y tambien se puede aplicar - como en un plano cartesiono
    halign = center # Alineación horizontal
    valign = top # Alineación vertical
    shadow_passes = 3
    shadow_size = 4
    shadow_color = $color0
    shadow_offset = 0, 0
    shadow_blur = 0
}


# Hours
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%H") </big></b>"
    color = $color6
    font_size = 180
    font_family = Geist Mono 10
    shadow_passes = 3
    shadow_size = 4
    position = 0, 0
    halign = center
    valign = center
    shadow_passes = 3
    shadow_size = 4
    shadow_color = $color0
}

# Minutes
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%M") </big></b>"
    color = $color6
    font_size = 180
    font_family = Geist Mono 10
    shadow_passes = 3
    shadow_size = 4
    position = 0, 210
    halign = center
    valign = center
    shadow_passes = 3
    shadow_size = 4
    shadow_color = $color0

}

# Today
label {
    monitor =
    text = cmd[update:18000000] bash -c 'echo "<b><big>$(date +%A)</big></b>"'
    color = $color7
    font_size = 42
    font_family = JetBrainsMono Nerd Font 10
    position = 0, -240
    halign = center
    valign = center
    shadow_passes = 3
    shadow_size = 4
    shadow_color = $color0
    shadow_offset = 0, 0
}

# Week
label {
    monitor =
    text = cmd[update:18000000] echo "<b> "$(date +'%d %b')" </b>"
    color = $color7
    font_size = 42
    font_family = JetBrainsMono Nerd Font 10

    position = 0, -300
    halign = center
    valign = center

    shadow_passes = 3
    shadow_size = 4
    shadow_color = $color0
}

input-field {
    monitor =
    size = 300, 70
    outline_thickness = 3

    dots_size = 0.26 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.64 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    dots_rouding = -1

    rounding = 26
    outer_color = $color0
    inner_color = $color0
    font_color = $color6
    fade_on_empty = true
    placeholder_text = <i>Contraseña...</i> # Text rendered in the input box when it's empty.

    position = 0, 120
    halign = center
    valign = bottom
}

# Degrees
label {
    monitor =
    text = cmd[update:18000000] echo "<b>Feels like<big> $(curl -s 'wttr.in?format=%t' | tr -d '+') </big></b>"
    color = $color7
    font_size = 24
    font_family = Geist Mono 10

    position = 0, 40
    halign = center
    valign = bottom

    shadow_passes = 3 
    shadow_size = 4
    shadow_color = $color0
}
