###########################
###    MY PROGRAMS     ###
###    For Biglex J    ###
###########################

### >> Path Apps <<

$kitty = kitty                                  # terminal
$konsole = konsole
$warp = /opt/warpdotdev/warp-terminal/warp
$fileManager = pcmanfm                          # gestor de archivos
$fileManager2 = XDG_CURRENT_DESKTOP=kde dolphin # fix - para manajador de colores y themasq
$brave = brave                                  # navegador
$edge = /opt/microsoft/msedge/msedge
$menu = rofi -show drun                          # lanzador
$menu2 = wofi --show drun --style ~/.config/wofi/style.css
$lockscreen = hyprlock                           # pantalla/fondo
$waypaper = waypaper
$vscode = code                                   # editor/código
$kate = kate
$kcolorchooser = kcolorchooser                   # diseño/gráfico
$kolourpaint = kolourpaint
$audacity = audacity                             # audio/música
$elisa = elisa
$kid3 = kid3s
$musescore = /home/biglexj/AppImage-Apps/MuseScore/MuseScore-Studio-4.4.4.243461245-x86_64.AppImage
$neothesia = /home/biglexj/AppImage-Apps/Neothesia/Neothesia.sh
$gwenview = gwenview                             # imagen/video
$qview = qview
$vlc = vlc
$localsend = localsend_app                       # comunicación
$telegram = /home/biglexj/AppImage-Apps/Telegram/Telegram
$scrcpy = scrcpy                                 # otros
$heroic = /home/biglexj/AppImage-Apps/Heroic-Games-Launcher/Heroic-2.15.2.AppImage
$upscayl = /home/biglexj/AppImage-Apps/Upscayl/upscayl-2.15.0-linux.AppImage


$mainMod = SUPER # Sets "Windows" key as main modifier

### >> Lanzadores / Sistema <<
bind = $mainMod, SPACE, exec, $menu
bind = $mainMod, R, exec, $menu2
bind = $mainMod, L, exec, $lockscreen
bind = $mainMod, W, exec, ~/.config/biglexj/control-center/wifimenu --rofi -s

### >> Bind Apps <<
bind = $mainMod, RETURN, exec, $kitty         # escenciales
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, F, exec, $fileManager2
bind = $mainMod, B, exec, $edge

bind = ctrl alt, Y, exec, $brave               # navegador
bind = ctrl alt, Q, exec, $warp               # terminal
bind = ctrl alt, K, exec, $konsole
bind = ctrl alt, V, exec, $vscode             # editor/código
bind = ctrl alt, H, exec, $kate
bind = ctrl alt, A, exec, $audacity           # audio
bind = ctrl alt, L, exec, $elisa
bind = ctrl alt, U, exec, $musescore
bind = ctrl alt, N, exec, $neothesia
bind = ctrl alt, X, exec, $kid3
bind = ctrl alt, C, exec, $kcolorchooser      # diseño/gráfico
bind = ctrl alt, P, exec, $kolourpaint
bind = ctrl alt, I, exec, $upscayl
bind = ctrl alt, G, exec, $gwenview           # imagen/video
bind = ctrl alt, J, exec, $qview
bind = ctrl alt, S, exec, $scrcpy
bind = ctrl alt, Z, exec, $vlc
bind = ctrl alt, R, exec, $localsend          # comunicación
bind = ctrl alt, P, exec, $telegram
bind = ctrl alt, H, exec, $heroic             # launcher/juegos

# Bind Scripts
bind = $mainMod SHIFT, W, exec, $waypaper
bind = $mainMod SHIFT, B, exec, ~/.config/biglexj/wallpaper-conf/wallpaper_select.sh
bind = $mainMod SHIFT, N, exec, ~/.config/biglexj/wallpaper-conf/random_wallpaper.sh
bind = $mainMod SHIFT, Q, exec, ~/.config/biglexj/scripts/reload-waybar.sh # Reiniciar
