
# Window Rules — Hyprland 0.55+ (hyprlang one-liner)
# Sintaxis: windowrule = efecto valor, match:class ^(regex)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

windowrule = stay_focused 1, match:class ^(Rofi)$
#windowrule = force_input 1, match:class ^(Rofi)$
windowrule = float 1, match:class ^(waypaper)$
windowrule = opacity 0.98 0.98, match:class ^(Code)$

windowrule = float 1, match:class ^(float_kitty)$
windowrule = size 1450 800, match:class ^(float_kitty)$

##############################
### WINDOWS AND WORKSPACES ###
##############################

windowrule = suppress_event maximize, match:class .*
